ahgl/urls.py
from django.conf import settings
from django.conf.urls.defaults import include, patterns, url
from django.conf.urls import patterns, url, include
from django.views.generic import ListView
from django.conf.urls.static import static
from django.forms import models as model_forms

from django.contrib import admin
admin.autodiscover()

from idios.views import ProfileUpdateView
from django_messages.views import compose

from profiles.models import Profile
from profiles.views import (MVPView, TeamListView, TeamDetailView, TeamAdminView,
                            StandingsView, TeamUpdateView, TeamSignupView,
                            MyProfileDetailView, ResendEmailConfirmation, TeamMembershipView,
                            TeamMembershipUpdateView, TeamMembershipCreateView,
                            TeamMembershipDeleteView, CasterListView,
                            JoinTeamView, InviteTeamMember)

from tournaments.views import (MatchDetailView, MatchListView, MatchReportView,
                               SubmitLineupView, GameListView, PlayerAdminView)
from tournaments.models import Tournament

from utils.views import StaticFileView, AccountBarView

from rest_framework import routers

from ahgl.api.views import games, matches, carousel, articles


router = routers.DefaultRouter()
router.register(r'games', games.GamesViewSet)
router.register(r'latest_news', articles.LatestNewsViewSet)
router.register(r'featured_matches', matches.FeaturedMatchesViewSet)
router.register(r'carousel', carousel.CarouselItemViewSet)

urlpatterns = patterns('',
    url(r'^api/', include(router.urls)),
)

urlpatterns += patterns('',
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("recaptcha_form.account_backend.urls")),
    url(r'^social/', include('social_auth.urls')),
    url(r"^profiles/profile/(?P<slug>[\w\._-]+)/$", MyProfileDetailView.as_view(), name="profile_detail"),
    url(r"^profiles/resend_confirmation/", ResendEmailConfirmation.as_view(), name="resend_confirmation"),
    url(r"^profiles/profile/(?P<slug>[\w\._-]+)/add_membership/$", TeamMembershipCreateView.as_view(), name="membership_create"),
    url(r"^profiles/edit/$", ProfileUpdateView.as_view(form_class=model_forms.modelform_factory(Profile, exclude=('user', 'signature', 'signature_html', 'time_zone', 'language', 'post_count', 'avatar',))), name="profile_edit"),
    url(r"^profiles/membership_edit/(?P<pk>[\d]+)/$", TeamMembershipUpdateView.as_view(), name="membership_edit"),
    url(r"^profiles/membership_delete/(?P<pk>[\d]+)/$", TeamMembershipDeleteView.as_view(), name="membership_delete"),
    url(r"^profiles/", include("idios.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^likes/", include("phileo.urls")),
    url(r"^announcements/", include("announcements.urls")),
    # url(r'^forum/', include('pybb.urls', namespace='pybb')),
    url(r'^messages/compose/(?P<recipient>[\+\w\.\-_]+)/$', compose, name='messages_compose_to'),  # we allow periods
    url(r'^messages/', include('django_messages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    # player admin controls
    url(r'^player_admin/$', PlayerAdminView.as_view(), name="player_admin"),
    url(r'^report_match/(?P<pk>[\d]+)/$', MatchReportView.as_view(), name="report_match"),
    # captain specific
    url(r'^submit_lineup/(?P<pk>[\d]+)/$', SubmitLineupView.as_view(), name="submit_lineup"),
    url(r'^(?P<tournament>[\w_-]+)/teams/(?P<slug>[\w_-]+)/edit/$', TeamUpdateView.as_view(), name='edit_team'),

    url(r'^archive/$', ListView.as_view(queryset=Tournament.objects.filter(status='C'), template_name="tournaments/archives.html"), name="archives"),
    url(r'^games/$', GameListView.as_view(), name='games'),
    url(r'^team/signup/$', TeamSignupView.as_view(), name='signup_team'),
    url(r'^team_admin/$', TeamAdminView.as_view(), name="team_admin"),
    url(r'^(?P<tournament>[\w_-]+)/mvp/$', MVPView.as_view(), name='mvp'),
    url(r'^(?P<tournament>[\w_-]+)/videos/$', GameListView.as_view(template_name="tournaments/videos.html", vod_only=True), name='videos'),
    url(r'^(?P<tournament>[\w_-]+)/games/$', GameListView.as_view(), name='games'),
    url(r'^(?P<tournament>[\w_-]+)/teams/(?P<team>[\w_-]+)/(?P<profile>[\w\._-]+)/games/$', GameListView.as_view(), name='games'),
    url(r'^(?P<tournament>[\w_-]+)/teams/(?P<team>[\w_-]+)/matches/$', MatchListView.as_view(template_name="tournaments/team_match_list.html"), name='matches'),
    url(r'^(?P<tournament>[\w_-]+)/teams/$', TeamListView.as_view(), name='teams'),
    #url(r'^(?P<tournament>[\w_-]+)/teams/create/$', TeamCreateView.as_view(), name='create_team'),
    url(r'^(?P<tournament>[\w_-]+)/teams/(?P<slug>[\w_-]+)/$', TeamDetailView.as_view(), name='team_page'),
    url(r'^(?P<tournament>[\w_-]+)/teams/(?P<team>[\w_-]+)/(?P<profile>[\w\._-]+)/$', TeamMembershipView.as_view(), name='player_profile'),
    url(r'^(?P<tournament>[\w_-]+)/schedule/$', MatchListView.as_view(template_name="tournaments/schedule.html"), name='schedule'),
    url(r'^(?P<tournament>[\w_-]+)/matches/$', MatchListView.as_view(), name='matches'),
    url(r'^(?P<tournament>[\w_-]+)/matches/(?P<pk>[\d]+)/$', MatchDetailView.as_view(), name='match_page'),
    #url(r'^(?P<tournament>[\w_-]+)/matches/(?P<date>[\d\\-]+)/(?P<home>[\w_-]+)-vs-(?P<away>[\w_-]+)$', MatchDetailView.as_view(), name='match_page'),
    url(r'^(?P<tournament>[\w_-]+)/standings/$', StandingsView.as_view(), name='standings'),
    url(r'^(?P<tournament>[\w_-]+)/invite_member/(?P<team>[\w_-]+)/$', InviteTeamMember.as_view(), name='invite_member'),
    url(r'^(?P<tournament>[\w_-]+)/join_team/(?P<team>[\w_-]+)/$', JoinTeamView.as_view(), name='join_team'),

    # Root of the site is the new Angular app, but keep the rest of the CMS pages around for posterity.
    url(r'^account/account_bar/$', AccountBarView.as_view()),
    url(r'^/?$', StaticFileView.as_view(path='static/js/app/dist/index.html')),
    
    url(r'^', include('cms.urls')),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ahgl/apps/tournaments/models.py
from collections import namedtuple
import posixpath
import logging
import random, math
from itertools import chain, count, takewhile, islice, groupby
import os.path

from django.db import models
from django.db.models import Q, Count, F
from django.utils.translation import ugettext_lazy as _
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.conf import settings
from django.core.exceptions import ValidationError
from django.template.defaultfilters import date, slugify
from django.utils import timezone

from cms.models.pluginmodel import CMSPlugin
from celery.execute import send_task
if "sorl.thumbnail" in settings.INSTALLED_APPS:
    from sorl.thumbnail import ImageField
else:
    from django.db.models import ImageField
if "notification" in settings.INSTALLED_APPS:
    from notification import models as notification
else:
    notification = None

from apps.profiles import RACES


logger = logging.getLogger(__name__)

def validate_wholenumber(value):
    if value < 1:
        raise ValidationError(u'{0} is not a whole number'.format(value))

class Tournament(models.Model):
    name = models.CharField(_("name"), max_length=50)
    slug = models.SlugField(max_length=50, primary_key=True)
    map_pool = models.ManyToManyField('Map')
    status = models.CharField(max_length=1, choices=(('C', 'Completed'), ('A', 'Active'), ('S', 'Signup'),), default='S', db_index=True)
    games_per_match = models.PositiveSmallIntegerField(default=5, verbose_name="Default Games per Match", validators=[validate_wholenumber])
    structure = models.CharField(max_length=1, choices=(('I', 'Individual'),('T', 'Team'),), default='I')
    
    def random_teams(self, amount=7):
        return self.teams.order_by('?')[:amount]
    
    def stages(self):
        return self.rounds.values('stage_name', 'stage_order').distinct().order_by('stage_order')
    
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('tournament', (), {'slug': self.slug,
                                   }
                )

class Map(models.Model):
    name = models.CharField(_("name"), max_length=50, primary_key=True)
    photo = ImageField(upload_to='map_photos', null=True, blank=True)
    # TODO:maybe add computed statistics later?
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)



BracketRow = namedtuple("BracketRow", "items, name")
TeamBracketRecord = namedtuple("TeamBracketRecord", "home_team_membership, away_team_membership, match, is_champion")
class TournamentRound(models.Model):
    order = models.IntegerField()
    tournament = models.ForeignKey('Tournament', related_name='rounds')
    teams = models.ManyToManyField('profiles.Team', related_name='rounds', through='TeamRoundMembership')
    stage_order = models.IntegerField()
    stage_name = models.CharField(max_length=40)
    structure = models.CharField(max_length=1, choices=(('G', 'Group'),('E', 'Elimination'),), default='G')
    published = models.BooleanField(default=False)
    
    @staticmethod
    def _round_name(count):
        return {1:"Champion", 2:"Finals", 4:"Semi-finals"}.get(count) or "Round of {0}".format(count)

    @staticmethod
    def _seed(bracket):
        # this only works for multiples of two
        len_base = math.log(len(bracket), 2)
        if int(len_base) != len_base:
            return []
        fbracket = [(None,0)]*len(bracket)
        fbracket[0] = bracket[0]
        stage_size = 2
        next_step = len(bracket)
        while stage_size <= len(bracket):
            step = next_step
            next_step = step // 2
            for i in range(0, len(bracket), step):
                fbracket[i+next_step] = bracket[stage_size - fbracket[i][0]-1]
            stage_size *= 2
        return fbracket
    
    def match_dict(self):
        queryset = self.matches.filter(published=True).values('id','home_team','away_team','tournament','winner','games__winner_team').annotate(wins=Count('games')).order_by('home_team','away_team')
        keyfunc = lambda match:(match['home_team'],match['away_team'])
        def makematch(match_group):
            ret = None
            for item in match_group:
                ret = ret or item
                if item['games__winner_team']:
                    ret['home_wins' if item['games__winner_team']==item['home_team'] else 'away_wins'] = item['wins']
            return ret
        return dict((frozenset(key),makematch(match_group)) for key, match_group in groupby(queryset,keyfunc))

    def elim_bracket(self):
        positions, participants = zip(*self._seed(list(enumerate(self.participants()))))
        match_dict = self.match_dict()
        print(match_dict)
        num_players = 0
        for wins_needed in takewhile(lambda x:participants, count(1)):
            num_players = len(participants)
            if num_players == 1:
                yield BracketRow([TeamBracketRecord(participants[0], None, None, True)], self._round_name(num_players))
            else:
                yield BracketRow([TeamBracketRecord(participants[i], participants[i+1], match_dict.get(frozenset((member.team_id for member in participants[i:i+2]))), False) for i in range(0, num_players, 2)], self._round_name(num_players))
            participants = [team_membership for team_membership in participants if team_membership.wins>=wins_needed]
        num_players = num_players // 2
        while num_players:
            if num_players == 1:
                yield BracketRow([TeamBracketRecord(None, None, None, True)], self._round_name(num_players))
            else:
                yield BracketRow([TeamBracketRecord(None, None, None, False)]*(num_players//2), self._round_name(num_players))
            num_players = num_players // 2
    
    def participants(self):
        queryset = self.team_membership.select_related('team')
        if self.structure=="G":
            return queryset.order_by('-wins', '-tiebreaker', 'team__seed')
        else:
            return queryset.order_by('team__seed')
    
    def __unicode__(self):
        return " : ".join((self.stage_name, unicode(self.order)))
    
    class Meta:
        ordering = ('-stage_order','order',)

class TeamRoundMembership(models.Model):
    tournamentround = models.ForeignKey('TournamentRound', db_index=True, related_name='team_membership')
    team = models.ForeignKey('profiles.Team', db_index=True, related_name='round_membership')
    wins = models.IntegerField(default=0, editable=False)
    losses = models.IntegerField(default=0, editable=False)
    tiebreaker = models.IntegerField(default=0, editable=False)
    #TODO: moving seeding here
    
    def update_stats(self):
        self.wins = self.team.match_wins.filter(published=True, tournament_round=self.tournamentround).count()
        self.losses = self.team.match_losses.filter(published=True, tournament_round=self.tournamentround).count()
        self.tiebreaker = self.team.game_wins.filter(match__published=True, match__tournament_round=self.tournamentround).count() \
                        - self.team.game_losses.filter(match__published=True, match__tournament_round=self.tournamentround).count()
        self.__class__.objects.filter(pk=self.pk).update(wins=self.wins, losses=self.losses, tiebreaker=self.tiebreaker)

    class Meta:
        db_table = 'tournaments_tournamentround_teams'
        unique_together = (('tournamentround', 'team'),)
        auto_created = True # LOL, this is a terrible hack that keeps add and remove around; only use this if all fields are auto

class Match(models.Model):
    structure = models.CharField(max_length=1, choices=(('I', 'Individual'),('T', 'Team'),), default='I')
    home_team = models.ForeignKey('profiles.Team', related_name="home_matches")
    away_team = models.ForeignKey('profiles.Team', related_name="away_matches")
    tournament = models.ForeignKey('Tournament', related_name='matches')
    tournament_round = models.ForeignKey('TournamentRound', related_name='matches')
    published = models.BooleanField(default=False)
    publish_date = models.DateField(blank=True, null=True) #set this when published
    creation_date = models.DateField()
    description = models.TextField(blank=True)
    referee = models.ForeignKey('profiles.Profile', null=True, blank=True, editable=False)
    # submitted lineups yet?
    home_submitted = models.BooleanField(default=False)
    away_submitted = models.BooleanField(default=False)
    home_submission_date = models.DateTimeField(blank=True, null=True, editable=False)
    away_submission_date = models.DateTimeField(blank=True, null=True, editable=False)
    winner = models.ForeignKey('profiles.Team', related_name="match_wins", blank=True, null=True, editable=False)
    loser = models.ForeignKey('profiles.Team', related_name="match_losses", blank=True, null=True, editable=False)    
    
    def update_winloss(self):
        for team in (self.home_team, self.away_team):
            team.wins = team.match_wins.filter(published=True).count()
            team.losses = team.match_losses.filter(published=True).count()
            team.save()
            try:
                membership = TeamRoundMembership.objects.get(team=team, tournamentround=self.tournament_round)
            except TeamRoundMembership.DoesNotExist:
                pass
            else:
                membership.wins = team.match_wins.filter(published=True, tournament_round=self.tournament_round).count()
                membership.losses = team.match_losses.filter(published=True, tournament_round=self.tournament_round).count()

ahgl/tournaments/templates/tournaments/_player_preview.html
{% load thumbnail %}
<div class="video-player-link-container {{last}}" style="max-width:{{width}}px;">
<p><a href="{{player.get_absolute_url}}">
{% thumbnail player.thumbnail thumb_size crop="center" as im %}
  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{player}}" />
{% empty %}
  <img src="{{ STATIC_URL }}images/default_profile.png" />
{% endthumbnail %}
</a></p>
<h3 class="t3">{{player}}{% if user.is_authenticated and game.winner_id == player.id or game.winner_team_id == player.id %}*{% endif %}</h3>
<p><a href="{{player.get_absolute_url}}">More about {{player}}</a></p>
</div>

ahgl/tournaments/templates/tournaments/archives.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Matches" %}{% endblock %}

{% block body %}
    <h2 class="title title-1 t1">{% trans "Past Tournaments" %}</h2>
    
    {% autopaginate tournament_list %}
    
    <ul class="unstyled">
    {% for tournament in tournament_list %}
        <li><h3 class="t2"><a href="/{{tournament.slug}}">{{ tournament.name }}</a></h3>
              <ul>
			    <li><a href="{% url videos tournament.slug %}">{% trans "Videos" %}</a></li>
          <li><a href="{% url schedule tournament.slug %}">{% trans "Schedule" %}</a></li>
			    <li><a href="{% url standings tournament.slug %}">{% trans "Team Standings" %}</a></li>
			    <li><a href="{% url teams tournament.slug %}">{% trans "Teams" %}</a></li>
              </ul>
        </li>
    {% empty %}
    	<li>No past tournaments</li>
    {% endfor %}
    </ul>
    
    {% paginate %}
    
{% endblock %}

ahgl/tournaments/templates/tournaments/map_list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Matches" %}{% endblock %}

{% block body %}
    <h1>{% trans "Map List" %}</h1>
    
    {% autopaginate match_list %}
    
    
    {% for match in match_list %}
    <h2>{{match.home_team}} vs {{match.away_team}} ({{match.creation_date}})</h2>
    
    {% with games=match.games_with_map %}
    
    <ul>
    {% for game in games %}
    <li>Game {{forloop.counter}} – {{game.map}} {% if game.is_ace %}(ACE){% endif %}</li>
    {% endfor %}
    </ul>
    {% endwith %}
    
    {% empty %}
    	<li>Map list not ready yet</li>
    {% endfor %}
    
    {% paginate %}
    
{% endblock %}

ahgl/tournaments/templates/tournaments/player_admin.html
{% extends "site_base.html" %}

{% load pagination_tags %}

{% block head_title %}Player Admin{% endblock %}

{% block content-class %}static-page{% endblock %}

{% block body %}
<h2 class="title title-1 t1">
Player Admin
</h2>
<h3 class="t2">Your Matches</h3>
{% for match in team_matches %}
<p>{% ifchanged %}<h4 class="f4">{{match.creation_date}}</h4>{% endifchanged %}<h4 class="f2 bold"><a href="{{match.home_team.get_absolute_url}}">{{match.home_team}}</a>{% if match.home_submitted %} (Lineup Submitted: {{match.home_submission_date|default_if_none:"Yes"}}){% endif %} vs <a href="{{match.away_team.get_absolute_url}}">{{match.away_team}}</a>{% if match.away_submitted %} (Lineup Submitted: {{match.away_submission_date|default_if_none:"Yes"}}){% endif %}</h2>
<h3 class="bold">Channel: AHGL-{{match.home_team.name|slugify|slice:":12"}}-{{match.away_team.name|slugify|slice:":12"}}</h3>

{% if match.home_submitted and match.away_submitted %}
  {% with games=match.games_for_lineup %}
    <table class="table">
    {% for game in games %}
      <tr><th>Game {{game.order}} – {{game.map}}</th>
      {% if game.is_ace or not game.home_player %}
        <td colspan="3">{% if game.is_ace %}ACE{% endif %}</td>
      {% else %}
        <td><a href="{{game.home_player.get_absolute_url}}">{{game.home_player}}.{{game.home_player.char_code|default_if_none:"xxx"}}</a> as {{game.get_home_races|join:", "}}</td>
        <td>vs</td>
        <td><a href="{{game.away_player.get_absolute_url}}">{{game.away_player}}.{{game.away_player.char_code|default_if_none:"xxx"}}</a> as {{game.get_away_races|join:", "}}</td>
      {% endif %}
    {% endfor %}
    </table>
  {% endwith %}
{% else %}
  {% with games=match.games_with_map %}
    <ul>
    {% for game in games %}
      <li>Game {{forloop.counter}} – {{game.map}} {% if game.is_ace %}(ACE){% endif %}</li>
    {% endfor %}
    </ul>
  {% endwith %}
  <a href="{% url submit_lineup pk=match.id %}">Submit Lineup</a>
{% endif %}
</p>
{% empty %}
  <p>No upcoming matches</p>
{% endfor %}


{% with match_list=report_match_list %}
{% autopaginate match_list %}

<h3 class="t2">Report a match</h3>
<ul class="unstyled">
{% for match in match_list %}
  {% ifchanged %}<h3>{{ match.creation_date }}</h3>{% endifchanged %}
    <li><a href="{% url report_match match.pk %}">{{match.home_team}} vs {{match.away_team}}</a></li>
{% empty %}
  <li>No matches to report</li>
{% endfor %}
</ul>

{% paginate %}
{% endwith %}

{% endblock %}

ahgl/tournaments/templates/tournaments/report_match_list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Select Match to Report" %}{% endblock %}

{% block body %}
    <h1>{% trans "Select Match to Report" %}</h1>
    
    {% with match_list=match_list %}
    {% autopaginate match_list %}
    
    <ul class="unstyled">
    {% for match in match_list %}
        {% ifchanged %}<h3>{{ match.creation_date }}</h3>{% endifchanged %}
        <li><a href="{% url report_match match.pk %}">{{match.home_team}} vs {{match.away_team}}</a></li>
    {% empty %}
        <li>No matches to report</li>
    {% endfor %}
    </ul>
    
    {% paginate %}
    {% endwith %}
    
{% endblock %}

ahgl/tournaments/templates/tournaments/schedule.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Matches" %}{% endblock %}

{% block content-class %}static-page schedule-page-template{% endblock %}
{% block body %}
    <h2 class="title title-1 t1">{% trans "Schedule" %}</h2>

<div class="content-section-1">
  {% regroup match_list by publish_date as date_list %}
    {% for date in date_list %}
   <div>
      <h3 class="f5 bold">
        <a data-toggle="collapse" href="#stage{{date.grouper|date:"dMY"}}" class="accordion-toggle" >
          {% firstof date.grouper|date:"M d, Y" "Not Published" %} +
        </a>
      </h3>
      <p></p>
      <div id="stage{{date.grouper|date:"dMY"}}" class="collapse">
        <div class="">
          <ul class="season-list-1">
            {% regroup date.list by tournament_round as round_list %}
            {% for round in round_list %}
            <li class="season-list-item">
            <h3 class="f5 bold">Division {{round.grouper.order}} ({{round.grouper.stage_name}})</h3>
            <ul class="week-list-1">
              {% for match in round.list %}
                <li class="week-list-item">
                  <a class="week-list-link alt-link-2 cf" href="{{match.get_absolute_url}}">
                  <span class="week-matchup-number f6">Matchup {{forloop.counter}}</span>
                  <span class="week-team-1 f2 bold">{{match.home_team.name}}</span>
                  <span class="versus t12">vs</span>
                  <span class="week-team-2 f2 bold">{{match.away_team.name}}</span>
                  <span class="week-view-games f6">View games »</span>
                  </a>
                </li>
              {% endfor %}
              </ul></li>
            {% endfor %}
          </ul>
        </div>
      <p>&nbsp;</p>
      </div>
     </div>
     {% endfor %}
</div>
{% endblock %}

ahgl/tournaments/templates/tournaments/team_match_list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Matches" %}{% endblock %}

{% block content-class %}static-page schedule-page-template{% endblock %}
{% block body %}
    <h2><a href="{% url team_page tournament=tournament_slug slug=team_slug %}" class="title title-1 t1"><span class="t3">Back to </span>{{team_slug}}</a></h2>
    {% autopaginate match_list %}
    
    <ul class="unstyled">
    {% for match in match_list %}
        {% ifchanged %}<h4 class="t3">{{match.tournament_round.stage_name}}</h4>{% endifchanged %}
        <li class="cf" style="float:none;">
        <h4 class="t2"><a href="{{match.get_absolute_url}}">{{match}}</a></h4>
        </li>
    {% empty %}
        <li>No matches yet</li>
    {% endfor %}
    </ul>
    
    {% paginate %}
    
{% endblock %}

ahgl/tournaments/templates/tournaments/videos.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}Videos{% endblock %}

{% block body %}
        <h2 class="title title-1 t1">Videos</h2>
      
        <div class="entry cf">
        
                <!-- start content -->
<div class="content-section-1">
  {% regroup game_list by match as match_list %}
    {% autopaginate match_list 5 %}
    {% for match in match_list %}
       <ul class="result-list cf">
        <h3 class="t11"><a href="{% url match_page tournament=tournament_slug pk=match.grouper.pk %}">{{match.grouper}}</a></h3><hr>
        {% for game in match.list %}
        <li class="result-excerpt{% if forloop.first %} first-in-row{% endif %}">
        <h3 class="result-excerpt-title">
        <a class="result-excerpt-link alt-link" href="{{game.vod}}" id="post-133" target="_blank"><span class="t8">{{match.grouper.home_team.name}}</span> <span class="t7">vs</span> <span class="t8">{{match.grouper.away_team.name}}</span></a><a href="{% url match_page tournament=tournament_slug pk=match.grouper.pk %}">Game {{forloop.counter}}</a>
        </h3>
        </li>
        {% endfor %}
        </ul>
    {% endfor %}
    {% paginate %}
</div>
</div>
{% endblock %}

ahgl/tournaments/templates/tournaments/view_lineup.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Matches" %}{% endblock %}

{% block body %}
    <h1>{% trans "Lineup" %}</h1>
    
    {% autopaginate match_list %}
    
    
    {% for match in match_list %}
    <h2>{{match.home_team}} vs {{match.away_team}}</h2>
    
    {% with games=match.games_with_related %}
    
    <table class="table">
    {% for game in games %}
    <tr><th>Game {{game.order}} – {{game.map}}</th>
    {% if game.is_ace %}
    <td>ACE</td><td></td><td></td>
    {% else %}
    <td><a href="{{game.home_player.get_absolute_url}}">{{game.home_player}}.{{game.home_player.char_code|default_if_none:"xxx"}}</a> as {{game.get_home_races|join:", "}}</td>
    <td>vs</td>
    <td><a href="{{game.away_player.get_absolute_url}}">{{game.get_away_races|join:", "}}.{{game.away_player.char_code|default_if_none:"xxx"}}</a> as {{game.get_away_race_display}}</td>
    {% endif %}
    {% endfor %}
    </table>
    {% endwith %}
    
    {% empty %}
         <li>Lineup not yet set</li>
    {% endfor %}
    
    {% paginate %}
    
{% endblock %}